// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaDicBackEnd.ApiService.Models;

#nullable disable

namespace PharmaDicBackEnd.ApiService.Migrations
{
    [DbContext(typeof(DrugLookupAppContext))]
    [Migration("20260625014353_AI")]
    partial class AI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.AIChatHistory", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChatID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("AIChatHistories", (string)null);
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.Disease", b =>
                {
                    b.Property<int>("DiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DiseaseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiseaseId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("WarningSigns")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiseaseId")
                        .HasName("PK__Diseases__69B533A9DF36CA37");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.DiseaseMedicine", b =>
                {
                    b.Property<int>("DiseaseId")
                        .HasColumnType("int")
                        .HasColumnName("DiseaseID");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiseaseId", "MedicineId")
                        .HasName("PK__DiseaseM__7D4721264AE26E97");

                    b.HasIndex("MedicineId");

                    b.ToTable("DiseaseMedicine", (string)null);
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.DrugInteraction", b =>
                {
                    b.Property<int>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InteractionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InteractionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicineId1")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID1");

                    b.Property<int>("MedicineId2")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID2");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InteractionId")
                        .HasName("PK__DrugInte__922C03766A653988");

                    b.HasIndex("MedicineId1");

                    b.HasIndex("MedicineId2");

                    b.ToTable("DrugInteractions");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FavoriteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("FavoriteId")
                        .HasName("PK__Favorite__CE74FAF5AF258C9F");

                    b.HasIndex("MedicineId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IngredientId")
                        .HasName("PK__Ingredie__BEAEB27A0F39FA2B");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<string>("Contraindications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosageForm")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SideEffects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Storage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strength")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Uses")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicineId")
                        .HasName("PK__Medicine__4F2128F0486E5BDD");

                    b.HasIndex("CategoryId");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.MedicineCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Medicine__19093A2B366D8A04");

                    b.ToTable("MedicineCategories");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.MedicineIngredient", b =>
                {
                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    b.Property<string>("Amount")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MedicineId", "IngredientId")
                        .HasName("PK__Medicine__F4CBC3D7D7AA2604");

                    b.HasIndex("IngredientId");

                    b.ToTable("MedicineIngredients");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.MedicineWarning", b =>
                {
                    b.Property<int>("WarningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WarningID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarningId"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    b.Property<string>("WarningContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarningLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WarningId")
                        .HasName("PK__Medicine__214571B874D10CCC");

                    b.HasIndex("MedicineId");

                    b.ToTable("MedicineWarnings");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.SearchHistory", b =>
                {
                    b.Property<int>("SearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SearchID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SearchId"));

                    b.Property<string>("Keyword")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("SearchDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SearchType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("SearchId")
                        .HasName("PK__SearchHi__21C53514CC980D92");

                    b.HasIndex("UserId");

                    b.ToTable("SearchHistory", (string)null);
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.Symptom", b =>
                {
                    b.Property<int>("SymptomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SymptomID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SymptomId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SymptomName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SymptomId")
                        .HasName("PK__Symptoms__D26ED8B6AE45016A");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Dược sĩ");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC37887F71");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105347A0EE942")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SymptomDisease", b =>
                {
                    b.Property<int>("SymptomId")
                        .HasColumnType("int")
                        .HasColumnName("SymptomID");

                    b.Property<int>("DiseaseId")
                        .HasColumnType("int")
                        .HasColumnName("DiseaseID");

                    b.HasKey("SymptomId", "DiseaseId")
                        .HasName("PK__SymptomD__54F58B8CCE6612A6");

                    b.HasIndex("DiseaseId");

                    b.ToTable("SymptomDisease", (string)null);
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.AIChatHistory", b =>
                {
                    b.HasOne("PharmaDicBackEnd.ApiService.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AIChatHistories_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.DiseaseMedicine", b =>
                {
                    b.HasOne("PharmaDicBackEnd.ApiService.Models.Disease", "Disease")
                        .WithMany("DiseaseMedicines")
                        .HasForeignKey("DiseaseId")
                        .IsRequired()
                        .HasConstraintName("FK__DiseaseMe__Disea__4F7CD00D");

                    b.HasOne("PharmaDicBackEnd.ApiService.Models.Medicine", "Medicine")
                        .WithMany("DiseaseMedicines")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK__DiseaseMe__Medic__5070F446");

                    b.Navigation("Disease");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.DrugInteraction", b =>
                {
                    b.HasOne("PharmaDicBackEnd.ApiService.Models.Medicine", "MedicineId1Navigation")
                        .WithMany("DrugInteractionMedicineId1Navigations")
                        .HasForeignKey("MedicineId1")
                        .IsRequired()
                        .HasConstraintName("FK__DrugInter__Medic__534D60F1");

                    b.HasOne("PharmaDicBackEnd.ApiService.Models.Medicine", "MedicineId2Navigation")
                        .WithMany("DrugInteractionMedicineId2Navigations")
                        .HasForeignKey("MedicineId2")
                        .IsRequired()
                        .HasConstraintName("FK__DrugInter__Medic__5441852A");

                    b.Navigation("MedicineId1Navigation");

                    b.Navigation("MedicineId2Navigation");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.Favorite", b =>
                {
                    b.HasOne("PharmaDicBackEnd.ApiService.Models.Medicine", "Medicine")
                        .WithMany("Favorites")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK__Favorites__Medic__5CD6CB2B");

                    b.HasOne("PharmaDicBackEnd.ApiService.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Favorites__UserI__5BE2A6F2");

                    b.Navigation("Medicine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.Medicine", b =>
                {
                    b.HasOne("PharmaDicBackEnd.ApiService.Models.MedicineCategory", "Category")
                        .WithMany("Medicines")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Medicines__Categ__3F466844");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.MedicineIngredient", b =>
                {
                    b.HasOne("PharmaDicBackEnd.ApiService.Models.Ingredient", "Ingredient")
                        .WithMany("MedicineIngredients")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK__MedicineI__Ingre__44FF419A");

                    b.HasOne("PharmaDicBackEnd.ApiService.Models.Medicine", "Medicine")
                        .WithMany("MedicineIngredients")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK__MedicineI__Medic__440B1D61");

                    b.Navigation("Ingredient");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.MedicineWarning", b =>
                {
                    b.HasOne("PharmaDicBackEnd.ApiService.Models.Medicine", "Medicine")
                        .WithMany("MedicineWarnings")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK__MedicineW__Medic__5FB337D6");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.SearchHistory", b =>
                {
                    b.HasOne("PharmaDicBackEnd.ApiService.Models.User", "User")
                        .WithMany("SearchHistories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__SearchHis__UserI__5812160E");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SymptomDisease", b =>
                {
                    b.HasOne("PharmaDicBackEnd.ApiService.Models.Disease", null)
                        .WithMany()
                        .HasForeignKey("DiseaseId")
                        .IsRequired()
                        .HasConstraintName("FK__SymptomDi__Disea__4CA06362");

                    b.HasOne("PharmaDicBackEnd.ApiService.Models.Symptom", null)
                        .WithMany()
                        .HasForeignKey("SymptomId")
                        .IsRequired()
                        .HasConstraintName("FK__SymptomDi__Sympt__4BAC3F29");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.Disease", b =>
                {
                    b.Navigation("DiseaseMedicines");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.Ingredient", b =>
                {
                    b.Navigation("MedicineIngredients");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.Medicine", b =>
                {
                    b.Navigation("DiseaseMedicines");

                    b.Navigation("DrugInteractionMedicineId1Navigations");

                    b.Navigation("DrugInteractionMedicineId2Navigations");

                    b.Navigation("Favorites");

                    b.Navigation("MedicineIngredients");

                    b.Navigation("MedicineWarnings");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.MedicineCategory", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("PharmaDicBackEnd.ApiService.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("SearchHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
